/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./components/provider";
import { socialMedia } from "../../data";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ahmed's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header className="bg-slate-900 text-white p-4 text-center">
          <p>Welcome to Next.js 15 Crash Course</p>
        </header> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <footer className="bg-[#040832] p-0 text-center w-full h-auto sm:p-4">
          <div className="sm:max-w-[90%] w-full m-auto flex h-full content-between">
            <div className=" h-full w-full">
              <div className="w-full  text-center">
                <h1 className="font-serif font-bold md:text-5xl text-4xl text-white">
                  Get In Touch
                </h1>
              </div>
              <div className="flex justify-between items-center w-full my-8">
                <div className=" w-full ">
                  <p className="font-sans font-medium text-white-100 text-xl mb-3 ">
                    Ready to collaborate or discuss opportunities? <br /> Feel
                    free to reach out.
                  </p>
                  <div className="flex flex-row gap-3 justify-center">
                    {socialMedia.map((item) => (
                      <a
                        key={item.id}
                        href={item.href}
                        target="/blank"
                        className=" "
                        download={item.download}
                      >
                        <div className="w-10 h-10 md:w-12 md:h-12 bg-gradient-to-r from-blue-500 to-blue-700 rounded-full flex items-center justify-center text-white transform hover:scale-110 animation shadow-lg shadow-blue-500/25 hover:opacity-100 transition-opacity ">
                          <img
                            src={item.img}
                            alt={item.alt}
                            className="w-5 h-5 md:w-7 md:h-7"
                          />
                        </div>
                      </a>
                    ))}
                  </div>
                </div>
              </div>
              <span className="my-4 block w-full border-t border-gray-500 border-opacity-50 pt-5">
                © 2025 Ahmed Salah All Rights Reserved
              </span>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
